In [1]:
import numpy as np
import pandas as pd
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
sample = pd.read_csv('/content/drive/My Drive/IIR_orientation/HW5/statistic_data_withCol.csv')

In [4]:
sample

No  Company  sex  age  Area  ...  Q6  Loyalty  AGE1  AREA1  平均滿意度
0    101        1    2    2     1  ...   4        4     2      1   3.67
1    102        1    1    3     1  ...   5        3     3      1   3.50
2    103        1    2    1     1  ...   4        4     1      1   4.00
3    104        1    2    3     1  ...   3        2     3      1   2.17
4    105        1    1    2     1  ...   4        4     2      1   4.17
..   ...      ...  ...  ...   ...  ...  ..      ...   ...    ...    ...
217  805        2    2    2     1  ...   4        3     2      1   3.17
218  806        2    1    2     1  ...   4        4     2      1   3.33
219  807        2    2    2     1  ...   4        3     2      1   3.67
220  808        2    1    1     1  ...   4        4     1      1   3.50
221  809        2    1    4     1  ...   3        2     3      1   3.50

[222 rows x 18 columns]

# Hypothesis testing #1
#### 設:
- H0: 婚姻 != 平均滿意度
- H1: 婚姻 = 平均滿意度
- 信心水準: 95%
- 統計檢定方法: t-test

#### 結果:
- p-value: 0.822
- 推論: 拒絕H1，婚姻與平均滿意度無相關

#### 程式碼:


In [5]:
sample['marriage'].unique()

array([1, 2])

In [6]:
from scipy.stats import ttest_ind

group1 = sample[sample['marriage']==1]['平均滿意度']
group2 = sample[sample['marriage']==2]['平均滿意度']

statval,pval = ttest_ind(group1,group2)
print("Test statistic:",statval)
print("P-value:",pval)
if pval <0.05:
  print("拒絕H0,有相關")
else:
  print("拒絕H1,無相關")



Test statistic: -0.22527480504041178
P-value: 0.8219746166170964
拒絕H1,無相關


# Hypothesis testing #2
#### 設:
- H0: 地區 != 平均滿意度
- H1: 地區 = 平均滿意度
- 信心水準: 95%
- 統計檢定方法: ANOVA

#### 結果:
- p-value: 0.000002 
- 推論: 拒絕H0，地區與平均滿意度有關

#### 程式碼:

In [7]:
sample['Area'].unique()

array([1, 2, 4, 3])

In [8]:
from scipy.stats import f_oneway

group1 = sample[sample['Area']==1]['平均滿意度']
group2 = sample[sample['Area']==2]['平均滿意度']
group3 = sample[sample['Area']==3]['平均滿意度']
group4 = sample[sample['Area']==4]['平均滿意度']

statval,pval = f_oneway(group1, group2, group3, group4)
print("Test statistic:",statval)
print("P-value:",pval)
if pval <0.05:
  print("拒絕H0,有相關")
else:
  print("拒絕H1,無相關")

Test statistic: 10.306719049755227
P-value: 2.2608181084405423e-06
拒絕H0,有相關


# Hypothesis testing #3
#### 設:
- H0: 年齡 != Q3(我對軟體問題的詢問，能有快速的回應)
- H1: 年齡 = Q3(我對軟體問題的詢問，能有快速的回應)
- 信心水準: 95%
- 統計檢定方法: Pearson's Chi-square test 

#### 結果:
- p-value: 0.0014
- 推論: 拒絕H0，年齡與Q3(我對軟體問題的詢問，能有快速的回應)有關

#### 程式碼:

In [9]:
sample['age'].unique()

array([2, 3, 1, 5, 4])

In [10]:
sample['Q3'].unique()

array([4, 1, 5, 3, 2])

In [11]:
from scipy.stats import chi2_contingency

CrossTable = pd.crosstab(sample['age'], sample['Q3'])
statval,pval,dof,ex = chi2_contingency(CrossTable)
print("Test statistic:",statval)
print("P-value:",pval)
if pval <0.05:
  print("拒絕H0,有相關")
else:
  print("拒絕H1,無相關")

Test statistic: 38.2987025539375
P-value: 0.0013717286350425086
拒絕H0,有相關
